version: "3.8"

services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      - db
    networks:
      - ghost-network

  db:
    image: mysql:5.7
    container_name: ghost-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    volumes:
      - ghost-mysql_data:/var/lib/mysql
    networks:
      - ghost-network

  volumes:
    ghost_content:
    ghost-mysql_data:
