services:
  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: db
      database__connection__database: ghostdb
      database__connection__user: ghost
      database__connection__password: ghostpass
      mail__transport: SMTP
      mail__options__host: mailhog
      mail__options__port: 1025
      mail__options__secureConnection: false
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      - db
    networks:
      - ghost-network

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: ghost-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
      innodb_force_recovery: 1
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ghost-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: ghost-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: ghost
      PMA_PASSWORD: ghostpass
    networks:
      - ghost-network

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: ghost-mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ghost-network

volumes:
  ghost_content:
  mysql_data:

networks:
  ghost-network:
    driver: bridge
