version: "3.8"

services:
  ghost:
    image: ghost:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == worker"
    ports:
      - target: 2368
        published: 80
        protocol: tcp
        mode: host
    environment:
      url: "http://localghost.sigma"
      database__client: mysql
      database__connection__host: db
      database__connection__database: ghostdb
      database__connection__user: ghost
      database__connection__password: ghostpass
      mail__transport: SMTP
      mail__options__host: mailhog
      mail__options__port: 1025
      mail__options__secureConnection: "false"
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      - db
    networks:
      - ghost-network

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ghost-network
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager" # Deploy phpMyAdmin on the manager node as well
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    environment:
      PMA_HOST: db
      PMA_USER: ghost
      PMA_PASSWORD: ghostpass
    networks:
      - ghost-network

  mailhog:
    image: mailhog/mailhog
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
    ports:
      - target: 1025
        published: 1025
        protocol: tcp
        mode: host
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
    networks:
      - ghost-network

volumes:
  ghost_content:
  mysql_data:

networks:
  ghost-network:
    driver: overlay # Overlay network for Swarm
