name: Deploy Ghost

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Swarm
        run: docker stack deploy -c docker-compose.yml blog
